### ISSUE TITLE
Test Case terlalu simple

### ISSUE THREAD

**Issue by adhywiranata** [botram/botram-api#6]
Test case terlalu simple. Karena ini CRUD, jangan hanya nge-test status response dan response nya sebagai object saja, tapi pastikan response-nya juga mengandung field-field terkait. Misal nge-post, pastikan field-field yang di post ada, dan jika put, pastikan memang data nya terupdate.

**Comment by qblol** [comment]
Test case improved, with total of 44 test. CI testing added.
Mark as closed.
